version: "3"

services:
  mongodb:
    image: mongo:4.2
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    networks:
      - crawler_network
  crawler:
    image: crawler:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=prod
    volumes:
      - .:/app/src
    networks:
      - crawler_network
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '8G'
        reservations:
          cpus: '4'
          memory: '8G'

networks:
  crawler_network:
    driver: bridge