version: "3"

services:
  mongodb:
    image: mongo:4.2
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    networks:
      - crawler_network
  crawler:
    image: crawler:latest
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=prod
    volumes:
      - .:/app/src
    networks:
      - crawler_network

networks:
  crawler_network:
    driver: bridge