version: "3"

services:
  mongodb:
    image: mongo:4.2
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data

